const EN = Object.freeze({
  "app.title": "My medication schedule",
  "app.loading_title": "Loading medication schedule",
  "app.loading_text": "Reading local data securely from Home Assistant.",
  "app.local_storage": "Stored locally in Home Assistant",
  "app.last_synced": "Last synced {time}",
  "app.refresh": "Refresh",
  "nav.overview": "Overview",
  "nav.medications": "Medications",
  "nav.regimens": "Intakes",
  "nav.history": "History",
  "common.active": "Active",
  "common.paused": "Paused",
  "common.save": "Save",
  "common.cancel": "Cancel",
  "common.edit": "Edit",
  "common.delete": "Delete",
  "common.details": "Details",
  "common.none": "None",
  "common.minutes_short": "min",
  "common.hours_short": "hr",
  "status.pending": "Pending",
  "status.partial": "Partial",
  "status.taken": "Taken",
  "status.skipped": "Skipped",
  "day.monday": "Monday",
  "day.tuesday": "Tuesday",
  "day.wednesday": "Wednesday",
  "day.thursday": "Thursday",
  "day.friday": "Friday",
  "day.saturday": "Saturday",
  "day.sunday": "Sunday",
  "relative.now": "now",
  "relative.before_minutes": "{minutes} min ago",
  "relative.in_minutes": "in {minutes} min",
  "relative.before_hours": "{hours} hr ago",
  "relative.in_hours": "in {hours} hr",
  "overview.eyebrow": "TODAY AT A GLANCE",
  "overview.waiting_one": "1 intake is waiting",
  "overview.waiting_many": "{count} intakes are waiting",
  "overview.all_done": "Everything is done",
  "overview.open_help": "Record the amounts actually taken or postpone the reminder.",
  "overview.no_open": "There are currently no open intakes.",
  "overview.next_intake": "Next intake",
  "overview.open_tickets": "Open tickets",
  "overview.check_required": "Please review",
  "overview.up_to_date": "Everything up to date",
  "overview.low_stock": "Low stock",
  "overview.well_stocked": "Well stocked",
  "overview.medications": "Medications",
  "overview.active_plans": "{count} active schedules",
  "overview.open_eyebrow": "OPEN TICKETS",
  "overview.due_intakes": "Due intakes",
  "overview.no_due_title": "No open intakes",
  "overview.no_due_text": "A ticket will appear here as soon as an intake becomes due.",
  "overview.stock_eyebrow": "STOCK",
  "overview.quick_view": "Quick overview",
  "overview.add_medication": "Medication",
  "overview.no_medications_title": "No medications yet",
  "overview.no_medications_text": "Create a medication first.",
  "ticket.due": "Due: {time}",
  "ticket.snoozed_until": "Snoozed until {time}",
  "ticket.deleted_medication": "Deleted medication",
  "ticket.already_taken": "{amount} already taken",
  "ticket.take_selection": "Mark selection taken",
  "ticket.snooze_30": "30 min",
  "ticket.snooze_60": "1 hr",
  "ticket.snooze_120": "2 hr",
  "ticket.custom_snooze": "Snooze until the selected time",
  "ticket.skip": "Skip",
  "medications.eyebrow": "MEDICINE CABINET",
  "medications.title": "Medications & stock",
  "medications.subtitle": "Manage package data, dose units and warning thresholds in one place.",
  "medications.create": "Create medication",
  "medications.empty_title": "No medications yet",
  "medications.empty_text": "Create your first medication with its initial stock.",
  "stock.reorder": "Reorder",
  "stock.available": "Available",
  "stock.no_details": "No additional details",
  "stock.warning_at": "Warning at {amount} {unit}",
  "stock.adjust": "Stock",
  "regimens.eyebrow": "SCHEDULES",
  "regimens.title": "Intakes & reminders",
  "regimens.subtitle": "Flexible weekly and interval schedules with individual notification targets.",
  "regimens.create": "Schedule intake",
  "regimens.empty_title": "No intakes scheduled",
  "regimens.empty_text": "Create a weekly schedule or an every-x-days interval.",
  "regimens.reminder_summary": "{targets} notification target(s) · repeats every {minutes} min",
  "schedule.every_day": "Every day, starting {date} at {time}",
  "schedule.every_days": "Every {days} days, starting {date} at {time}",
  "schedule.weekly_group": "{days} · {times}",
  "history.eyebrow": "LOG",
  "history.title": "Intake history",
  "history.subtitle": "Scheduled and actual time together with the doses deducted from stock.",
  "history.status": "Status",
  "history.intake": "Intake",
  "history.scheduled": "Scheduled",
  "history.actual": "Actual",
  "history.deviation": "Deviation",
  "history.doses": "Doses",
  "history.deleted_schedule": "Deleted schedule",
  "history.empty_title": "No history yet",
  "history.empty_text": "Completed and skipped intakes are logged here.",
  "med_form.eyebrow": "MEDICATION",
  "med_form.edit_title": "Edit medication",
  "med_form.new_title": "New medication",
  "med_form.dialog_label": "Edit medication",
  "med_form.name": "Name",
  "med_form.name_placeholder": "e.g. Metformin",
  "med_form.manufacturer": "Manufacturer",
  "med_form.manufacturer_placeholder": "e.g. 1A Pharma",
  "med_form.barcode": "Barcode / product code",
  "med_form.barcode_placeholder": "Scan or product number",
  "med_form.strength": "Strength",
  "med_form.strength_placeholder": "e.g. 500 mg",
  "med_form.form": "Dosage form",
  "med_form.form_placeholder": "Tablet, drops, …",
  "med_form.unit": "Stock unit",
  "med_form.unit_default": "pieces",
  "med_form.unit_placeholder": "pieces, ml, sprays, …",
  "med_form.stock": "Current stock",
  "med_form.threshold": "Warning threshold",
  "med_form.notes": "Notes",
  "med_form.notes_placeholder": "Optional notes",
  "reg_form.eyebrow": "INTAKE SCHEDULE",
  "reg_form.edit_title": "Edit intake",
  "reg_form.new_title": "New intake",
  "reg_form.dialog_label": "Edit intake",
  "reg_form.name": "Name",
  "reg_form.name_placeholder": "e.g. Lunchtime medication",
  "reg_form.status": "Status",
  "reg_form.medications_dose": "Medications & dose",
  "reg_form.add_medication": "Add another medication",
  "reg_form.rhythm": "Schedule type",
  "reg_form.weekly": "Weekly by weekday",
  "reg_form.interval": "Every x days",
  "reg_form.repeat": "Remind again after (minutes)",
  "reg_form.weekdays_times": "Weekdays and times",
  "reg_form.multiple_times_help": "Separate multiple times with commas.",
  "reg_form.interval_title": "Interval",
  "reg_form.every_days": "Every x days",
  "reg_form.start_date": "Start date",
  "reg_form.time": "Time",
  "reg_form.notify_services": "Notification services",
  "reg_form.notify_placeholder": "notify.mobile_app_my_phone",
  "reg_form.notify_help": "Separate multiple services with commas. Action buttons are added automatically.",
  "reg_form.scripts": "Scripts for every reminder",
  "reg_form.script_placeholder": "script.medication_reminder",
  "reg_form.instructions": "Intake instructions",
  "reg_form.instructions_placeholder": "e.g. Take with a glass of water and food",
  "reg_form.save": "Save schedule",
  "reg_form.choose_medication": "Choose medication",
  "reg_form.remove": "Remove",
  "action.medication_deleted": "Medication deleted.",
  "action.regimen_deleted": "Intake schedule deleted.",
  "action.stock_updated": "Stock updated.",
  "action.reminder_snoozed": "Reminder postponed.",
  "action.reminder_snoozed_until": "Reminder postponed until the selected time.",
  "action.intake_skipped": "Intake marked as skipped.",
  "action.intake_recorded": "Intake saved and stock deducted.",
  "action.medication_saved": "Medication saved.",
  "action.regimen_saved": "Intake schedule saved.",
  "confirm.delete_medication": "Delete this medication?",
  "confirm.delete_regimen": "Delete this intake schedule? Open tickets will also be removed.",
  "confirm.skip": "Skip this intake? Stock will not be changed.",
  "prompt.stock": "Enter the stock adjustment (e.g. 20 or -2):",
  "error.generic": "The action could not be completed.",
  "error.create_medication_first": "Create at least one medication first.",
  "error.select_time": "Select a time first.",
  "error.future_snooze": "The snooze time must be in the future.",
  "error.select_dose": "Select at least one dose.",
  "error.duplicate_medication": "A medication may only occur once per schedule.",
  "error.invalid_time": "Invalid time for {day}.",
  "error.select_weekday": "Select at least one weekday.",
  "error.not_configured": "Medication Reminder is not configured.",
  "error.medication_in_use": "This medication is still used by an intake schedule.",
  "error.negative_stock": "Stock cannot become negative.",
  "error.dose_exceeds": "The taken dose exceeds the remaining planned dose.",
  "error.not_enough_stock": "Not enough stock for {medication}.",
  "error.no_dose": "No dose was selected.",
  "error.only_open_snooze": "Only open intakes can be snoozed.",
  "error.name_required": "A name is required.",
  "error.unknown_medication": "The selected medication no longer exists.",
  "error.medication_duplicate": "A medication may only occur once per schedule.",
  "error.medication_required": "At least one medication is required.",
  "error.repeat_range": "The reminder interval must be between 5 and 1440 minutes.",
  "error.every_days_range": "The day interval must be between 1 and 365.",
  "error.schedule_type": "This schedule type is not supported.",
  "error.invalid_snooze": "The snooze time is invalid.",
  "error.invalid_time_generic": "One of the entered times is invalid.",
  "error.invalid_value": "One of the entered values is invalid."
});

const DE = Object.freeze({
  "app.title": "Mein Medikamentenplan",
  "app.loading_title": "Medikamentenplan wird geladen",
  "app.loading_text": "Lokale Daten werden sicher aus Home Assistant gelesen.",
  "app.local_storage": "Lokal in Home Assistant gespeichert",
  "app.last_synced": "Zuletzt synchronisiert {time}",
  "app.refresh": "Aktualisieren",
  "nav.overview": "Übersicht",
  "nav.medications": "Medikamente",
  "nav.regimens": "Einnahmen",
  "nav.history": "Verlauf",
  "common.active": "Aktiv",
  "common.paused": "Pausiert",
  "common.save": "Speichern",
  "common.cancel": "Abbrechen",
  "common.edit": "Bearbeiten",
  "common.delete": "Löschen",
  "common.details": "Details",
  "common.none": "Keine",
  "common.minutes_short": "Min.",
  "common.hours_short": "Std.",
  "status.pending": "Offen",
  "status.partial": "Teilweise",
  "status.taken": "Genommen",
  "status.skipped": "Ausgelassen",
  "day.monday": "Montag",
  "day.tuesday": "Dienstag",
  "day.wednesday": "Mittwoch",
  "day.thursday": "Donnerstag",
  "day.friday": "Freitag",
  "day.saturday": "Samstag",
  "day.sunday": "Sonntag",
  "relative.now": "jetzt",
  "relative.before_minutes": "vor {minutes} Min.",
  "relative.in_minutes": "in {minutes} Min.",
  "relative.before_hours": "vor {hours} Std.",
  "relative.in_hours": "in {hours} Std.",
  "overview.eyebrow": "HEUTE IM BLICK",
  "overview.waiting_one": "1 Einnahme wartet",
  "overview.waiting_many": "{count} Einnahmen warten",
  "overview.all_done": "Alles erledigt",
  "overview.open_help": "Erfasse die tatsächlich genommenen Mengen oder verschiebe die Erinnerung.",
  "overview.no_open": "Aktuell sind keine Einnahmen offen.",
  "overview.next_intake": "Nächste Einnahme",
  "overview.open_tickets": "Offene Vorgänge",
  "overview.check_required": "Bitte prüfen",
  "overview.up_to_date": "Alles aktuell",
  "overview.low_stock": "Niedriger Bestand",
  "overview.well_stocked": "Gut versorgt",
  "overview.medications": "Medikamente",
  "overview.active_plans": "{count} aktive Pläne",
  "overview.open_eyebrow": "OFFENE TICKETS",
  "overview.due_intakes": "Fällige Einnahmen",
  "overview.no_due_title": "Keine offenen Einnahmen",
  "overview.no_due_text": "Sobald eine Einnahme fällig wird, erscheint sie hier.",
  "overview.stock_eyebrow": "BESTÄNDE",
  "overview.quick_view": "Schneller Überblick",
  "overview.add_medication": "Medikament",
  "overview.no_medications_title": "Noch keine Medikamente",
  "overview.no_medications_text": "Lege zuerst ein Medikament an.",
  "ticket.due": "Soll: {time}",
  "ticket.snoozed_until": "Schlummert bis {time}",
  "ticket.deleted_medication": "Gelöschtes Medikament",
  "ticket.already_taken": "{amount} bereits genommen",
  "ticket.take_selection": "Auswahl genommen",
  "ticket.snooze_30": "30 Min.",
  "ticket.snooze_60": "1 Std.",
  "ticket.snooze_120": "2 Std.",
  "ticket.custom_snooze": "Bis zur gewählten Zeit schlummern",
  "ticket.skip": "Auslassen",
  "medications.eyebrow": "APOTHEKE",
  "medications.title": "Medikamente & Bestände",
  "medications.subtitle": "Packungsdaten, Dosiseinheit und Warnschwellen zentral verwalten.",
  "medications.create": "Medikament anlegen",
  "medications.empty_title": "Noch keine Medikamente",
  "medications.empty_text": "Erstelle dein erstes Medikament samt Anfangsbestand.",
  "stock.reorder": "Nachbestellen",
  "stock.available": "Verfügbar",
  "stock.no_details": "Keine Zusatzangaben",
  "stock.warning_at": "Warnung ab {amount} {unit}",
  "stock.adjust": "Bestand",
  "regimens.eyebrow": "ZEITPLÄNE",
  "regimens.title": "Einnahmen & Erinnerungen",
  "regimens.subtitle": "Flexible Wochen- und Intervallpläne mit eigenen Benachrichtigungszielen.",
  "regimens.create": "Einnahme planen",
  "regimens.empty_title": "Noch keine Einnahmen geplant",
  "regimens.empty_text": "Erstelle einen Wochenplan oder einen Rhythmus alle x Tage.",
  "regimens.reminder_summary": "{targets} Benachrichtigungsziel(e) · Wiederholung alle {minutes} Min.",
  "schedule.every_day": "Jeden Tag, ab {date} um {time}",
  "schedule.every_days": "Alle {days} Tage, ab {date} um {time}",
  "schedule.weekly_group": "{days} · {times}",
  "history.eyebrow": "PROTOKOLL",
  "history.title": "Einnahmeverlauf",
  "history.subtitle": "Soll- und Ist-Zeitpunkt sowie tatsächlich abgebuchte Dosen.",
  "history.status": "Status",
  "history.intake": "Einnahme",
  "history.scheduled": "Geplant",
  "history.actual": "Tatsächlich",
  "history.deviation": "Abweichung",
  "history.doses": "Dosen",
  "history.deleted_schedule": "Gelöschter Plan",
  "history.empty_title": "Noch kein Verlauf",
  "history.empty_text": "Abgeschlossene und ausgelassene Einnahmen werden hier protokolliert.",
  "med_form.eyebrow": "MEDIKAMENT",
  "med_form.edit_title": "Medikament bearbeiten",
  "med_form.new_title": "Neues Medikament",
  "med_form.dialog_label": "Medikament bearbeiten",
  "med_form.name": "Name",
  "med_form.name_placeholder": "z. B. Metformin",
  "med_form.manufacturer": "Hersteller",
  "med_form.manufacturer_placeholder": "z. B. 1A Pharma",
  "med_form.barcode": "Barcode / PZN",
  "med_form.barcode_placeholder": "Scan- oder Artikelnummer",
  "med_form.strength": "Wirkstärke",
  "med_form.strength_placeholder": "z. B. 500 mg",
  "med_form.form": "Darreichungsform",
  "med_form.form_placeholder": "Tablette, Tropfen, …",
  "med_form.unit": "Bestandseinheit",
  "med_form.unit_default": "Stück",
  "med_form.unit_placeholder": "Stück, ml, Hübe, …",
  "med_form.stock": "Aktueller Bestand",
  "med_form.threshold": "Warnschwelle",
  "med_form.notes": "Notizen",
  "med_form.notes_placeholder": "Optionale Hinweise",
  "reg_form.eyebrow": "EINNAHMEPLAN",
  "reg_form.edit_title": "Einnahme bearbeiten",
  "reg_form.new_title": "Neue Einnahme",
  "reg_form.dialog_label": "Einnahme bearbeiten",
  "reg_form.name": "Bezeichnung",
  "reg_form.name_placeholder": "z. B. Mittagsmedikation",
  "reg_form.status": "Status",
  "reg_form.medications_dose": "Medikamente & Dosis",
  "reg_form.add_medication": "Weiteres Medikament",
  "reg_form.rhythm": "Rhythmus",
  "reg_form.weekly": "Wöchentlich nach Wochentag",
  "reg_form.interval": "Alle x Tage",
  "reg_form.repeat": "Erneut erinnern nach (Min.)",
  "reg_form.weekdays_times": "Wochentage und Uhrzeiten",
  "reg_form.multiple_times_help": "Mehrere Uhrzeiten mit Komma trennen.",
  "reg_form.interval_title": "Intervall",
  "reg_form.every_days": "Alle x Tage",
  "reg_form.start_date": "Startdatum",
  "reg_form.time": "Uhrzeit",
  "reg_form.notify_services": "Benachrichtigungsdienste",
  "reg_form.notify_placeholder": "notify.mobile_app_mein_handy",
  "reg_form.notify_help": "Mehrere Dienste mit Komma trennen. Aktionsbuttons werden automatisch ergänzt.",
  "reg_form.scripts": "Scripts bei jeder Erinnerung",
  "reg_form.script_placeholder": "script.medikamenten_erinnerung",
  "reg_form.instructions": "Einnahmehinweis",
  "reg_form.instructions_placeholder": "z. B. Mit einem Glas Wasser und zum Essen",
  "reg_form.save": "Plan speichern",
  "reg_form.choose_medication": "Medikament wählen",
  "reg_form.remove": "Entfernen",
  "action.medication_deleted": "Medikament gelöscht.",
  "action.regimen_deleted": "Einnahmeplan gelöscht.",
  "action.stock_updated": "Bestand aktualisiert.",
  "action.reminder_snoozed": "Erinnerung verschoben.",
  "action.reminder_snoozed_until": "Erinnerung bis zur gewählten Zeit verschoben.",
  "action.intake_skipped": "Einnahme als ausgelassen markiert.",
  "action.intake_recorded": "Einnahme gespeichert und Bestand abgebucht.",
  "action.medication_saved": "Medikament gespeichert.",
  "action.regimen_saved": "Einnahmeplan gespeichert.",
  "confirm.delete_medication": "Dieses Medikament wirklich löschen?",
  "confirm.delete_regimen": "Diesen Einnahmeplan wirklich löschen? Offene Vorgänge werden ebenfalls entfernt.",
  "confirm.skip": "Diese Einnahme auslassen? Der Bestand wird nicht verändert.",
  "prompt.stock": "Bestandsänderung eingeben (z. B. 20 oder -2):",
  "error.generic": "Die Aktion konnte nicht ausgeführt werden.",
  "error.create_medication_first": "Lege zuerst mindestens ein Medikament an.",
  "error.select_time": "Bitte zuerst eine Uhrzeit auswählen.",
  "error.future_snooze": "Die Schlummerzeit muss in der Zukunft liegen.",
  "error.select_dose": "Wähle mindestens eine Dosis aus.",
  "error.duplicate_medication": "Ein Medikament darf pro Plan nur einmal vorkommen.",
  "error.invalid_time": "Ungültige Uhrzeit bei {day}.",
  "error.select_weekday": "Wähle mindestens einen Wochentag.",
  "error.not_configured": "Medication Reminder ist nicht eingerichtet.",
  "error.medication_in_use": "Dieses Medikament wird noch in einem Einnahmeplan verwendet.",
  "error.negative_stock": "Der Bestand darf nicht negativ werden.",
  "error.dose_exceeds": "Die eingenommene Dosis überschreitet die noch geplante Dosis.",
  "error.not_enough_stock": "Der Bestand von {medication} reicht nicht aus.",
  "error.no_dose": "Es wurde keine Dosis ausgewählt.",
  "error.only_open_snooze": "Nur offene Einnahmen können geschlummert werden.",
  "error.name_required": "Ein Name ist erforderlich.",
  "error.unknown_medication": "Das ausgewählte Medikament existiert nicht mehr.",
  "error.medication_duplicate": "Ein Medikament darf pro Plan nur einmal vorkommen.",
  "error.medication_required": "Mindestens ein Medikament ist erforderlich.",
  "error.repeat_range": "Das Erinnerungsintervall muss zwischen 5 und 1440 Minuten liegen.",
  "error.every_days_range": "Das Tagesintervall muss zwischen 1 und 365 liegen.",
  "error.schedule_type": "Dieser Zeitplantyp wird nicht unterstützt.",
  "error.invalid_snooze": "Die Schlummerzeit ist ungültig.",
  "error.invalid_time_generic": "Eine der eingegebenen Uhrzeiten ist ungültig.",
  "error.invalid_value": "Einer der eingegebenen Werte ist ungültig."
});

export const CATALOGS = Object.freeze({ en: EN, de: DE });

export function resolveLanguage(hass) {
  const requested = String(hass?.language || hass?.locale?.language || "en")
    .toLowerCase().split("-")[0];
  return Object.hasOwn(CATALOGS, requested) ? requested : "en";
}

export function createTranslator(language) {
  const catalog = CATALOGS[language] || EN;
  return (key, variables = {}) => {
    const template = catalog[key] ?? EN[key] ?? key;
    return template.replace(/\{(\w+)\}/g, (_match, name) => String(variables[name] ?? `{${name}}`));
  };
}
