const EN = Object.freeze({
  "app.title": "Medication",
  "app.subtitle": "Plans, stock and intake history",
  "app.loading_title": "Loading",
  "app.loading_text": "Reading local data from Home Assistant.",
  "app.local_storage": "Stored locally in Home Assistant",
  "app.last_synced": "Synced {time}",
  "app.refresh": "Refresh",
  "app.record_unplanned": "Record intake",
  "app.data_management": "Backup and restore",
  "app.delete_all_data": "Delete all data",
  "app.more": "More actions",

  "card.name": "Medication Reminder",
  "card.description": "Due medication intakes with record, snooze and skip controls.",
  "card.title_default": "Medication",
  "card.nothing_due": "Nothing due right now.",
  "card.nothing_open": "No open intakes.",
  "card.upcoming": "Coming up",
  "card.stock": "Stock",
  "card.not_configured": "Medication Reminder is not set up yet.",
  "card.loading": "Loading…",
  "card.record": "Record",
  "card.more_open": "{count} more open",
  "card.open_panel": "Open the medication panel",
  "card.editor.title": "Title",
  "card.editor.mode": "Show",
  "card.editor.mode_due": "Only intakes that are due",
  "card.editor.mode_open": "All open intakes",
  "card.editor.max": "Maximum intakes",
  "card.editor.allow_partial": "Editable dose amounts",
  "card.editor.show_snooze": "Snooze buttons",
  "card.editor.show_skip": "Skip button",
  "card.editor.show_upcoming": "Upcoming intakes",
  "card.editor.upcoming_count": "Number of upcoming intakes",
  "card.editor.show_stock": "Stock overview",
  "card.editor.stock_filter": "Stock entries",
  "card.editor.stock_all": "All medications",
  "card.editor.stock_low": "Only low stock",

  "nav.overview": "Overview",
  "nav.medications": "Medications",
  "nav.regimens": "Plans",
  "nav.history": "History",

  "common.active": "Active",
  "common.paused": "Paused",
  "common.save": "Save",
  "common.cancel": "Cancel",
  "common.edit": "Edit",
  "common.delete": "Delete",
  "common.details": "Details",
  "common.none": "None",
  "common.close": "Close",
  "common.minutes_short": "min",
  "common.days_short": "d",
  "common.optional": "optional",
  "common.advanced": "Advanced",
  "common.all": "All",
  "common.search": "Search",

  "status.pending": "Open",
  "status.partial": "Partial",
  "status.taken": "Taken",
  "status.skipped": "Skipped",
  "status.missed": "Missed",

  "day.monday": "Monday",
  "day.tuesday": "Tuesday",
  "day.wednesday": "Wednesday",
  "day.thursday": "Thursday",
  "day.friday": "Friday",
  "day.saturday": "Saturday",
  "day.sunday": "Sunday",
  "day.short.monday": "Mon",
  "day.short.tuesday": "Tue",
  "day.short.wednesday": "Wed",
  "day.short.thursday": "Thu",
  "day.short.friday": "Fri",
  "day.short.saturday": "Sat",
  "day.short.sunday": "Sun",

  "relative.now": "now",
  "relative.before_minutes": "{minutes} min ago",
  "relative.in_minutes": "in {minutes} min",
  "relative.before_hours": "{hours} h ago",
  "relative.in_hours": "in {hours} h",
  "relative.before_days": "{days} d ago",
  "relative.in_days": "in {days} d",

  "overview.due_now": "Due now",
  "overview.due_later": "Scheduled later today",
  "overview.upcoming": "Coming up",
  "overview.no_due_title": "Nothing to take right now",
  "overview.no_due_text": "Open intakes appear here as soon as they are due.",
  "overview.no_upcoming": "No active plan has a next date.",
  "overview.warnings": "Needs attention",
  "overview.metric_open": "Open intakes",
  "overview.metric_due": "Due now",
  "overview.metric_adherence": "Adherence {days} d",
  "overview.metric_low": "Low stock",
  "overview.no_medications_title": "No medications yet",
  "overview.no_medications_text": "Add a medication and its first package to get started.",
  "overview.add_medication": "Add medication",
  "overview.low_stock_warning": "{name}: {stock} {unit} left (warning at {threshold})",
  "overview.expiry_warning": "{name}: package {package} expires {date}",
  "overview.expired_warning": "{name}: package {package} expired on {date}",
  "overview.no_warnings": "No warnings.",

  "ticket.due": "Planned {time}",
  "ticket.snoozed_until": "snoozed until {time}",
  "ticket.take_selection": "Record selection",
  "ticket.take_all": "Record all",
  "ticket.snooze": "Snooze",
  "ticket.snooze_30": "30 min",
  "ticket.snooze_60": "1 h",
  "ticket.snooze_120": "2 h",
  "ticket.custom_snooze": "Snooze until a chosen time",
  "ticket.postpone_tomorrow": "Shift cycle to tomorrow",
  "ticket.skip": "Skip",
  "ticket.qr": "Intake QR code",
  "ticket.already_taken": "{amount} already taken",
  "ticket.take_from": "Take from {packages}",
  "ticket.deleted_medication": "Deleted medication",
  "ticket.unplanned": "Unplanned intake",
  "ticket.orphan_plan": "Plan no longer exists",
  "ticket.overdue": "Overdue",
  "ticket.ad_hoc": "One-off",
  "ticket.reason": "Reason: {reason}",

  "medications.title": "Medications",
  "medications.subtitle": "Master data, packages and derived stock.",
  "medications.create": "New medication",
  "medications.empty_title": "No medications",
  "medications.empty_text": "Create a medication, then add its packages.",

  "stock.available": "In stock",
  "stock.reorder": "Reorder",
  "stock.empty": "Empty",
  "stock.no_details": "No further details",
  "stock.warning_at": "Warning at {amount} {unit}",
  "stock.supply": "lasts about {days} d",
  "stock.supply_unknown": "no active plan",
  "stock.packages": "Packages",
  "stock.no_packages": "No packages yet.",
  "stock.add_package": "Add package",
  "stock.next_package": "Next: {package}",

  "package.remaining": "{amount} of {initial} {unit} left",
  "package.lot": "LOT {lot}",
  "package.expires": "expires {date}",
  "package.expired": "expired {date}",
  "package.no_expiry": "no expiry date",
  "package.code": "QR code",
  "package.edit": "Edit package",
  "package.delete": "Delete package",

  "regimens.title": "Intake plans",
  "regimens.subtitle": "When which medication is due and who gets notified.",
  "regimens.create": "New plan",
  "regimens.empty_title": "No plans",
  "regimens.empty_text": "A plan defines times, doses and reminders.",
  "schedule.every_day": "Every day at {time}, from {date}",
  "schedule.every_days": "Every {days} days at {time}, from {date}",
  "schedule.weekly_group": "{days} · {times}",
  "regimens.next": "Next: {time}",
  "regimens.no_next": "No upcoming date",
  "regimens.reminder_summary": "{targets} notification targets · repeat every {minutes} min",
  "regimens.reminder_none": "No notification target · panel only",
  "regimens.window": "reminders stop {minutes} min after the due time",
  "regimens.auto_miss": "auto-marked as missed after {minutes} min",

  "history.title": "History",
  "history.subtitle": "Planned versus actual intake, including package batches.",
  "history.export_title": "Export date range",
  "history.export_help": "Only completed, skipped and missed entries are exported.",
  "history.export_from": "From",
  "history.export_to": "To",
  "history.export_json": "JSON",
  "history.export_csv": "CSV",
  "history.export_done": "{count} entries exported.",
  "history.export_empty": "No entries in this date range.",
  "history.status": "Status",
  "history.intake": "Intake",
  "history.scheduled": "Planned",
  "history.actual": "Actual",
  "history.deviation": "Deviation",
  "history.doses": "Doses",
  "history.packages": "Packages: {packages}",
  "history.deleted_schedule": "Deleted plan",
  "history.empty_title": "No history yet",
  "history.empty_text": "Recorded and skipped intakes appear here.",
  "history.filter_status": "Status",
  "history.filter_search": "Filter by medication or plan",
  "history.adherence": "Adherence over {days} days: {rate}% of {total} planned intakes",
  "history.adherence_none": "Not enough planned intakes for an adherence value yet.",
  "history.counts": "{taken} taken · {partial} partial · {skipped} skipped · {missed} missed",

  "med_form.new_title": "New medication",
  "med_form.edit_title": "Edit medication",
  "med_form.dialog_label": "Medication",
  "med_form.name": "Name",
  "med_form.name_placeholder": "Ibuprofen",
  "med_form.manufacturer": "Manufacturer",
  "med_form.manufacturer_placeholder": "Ratiopharm",
  "med_form.barcode": "Barcode / product code",
  "med_form.barcode_placeholder": "PZN or EAN",
  "med_form.strength": "Strength",
  "med_form.strength_placeholder": "400 mg",
  "med_form.form": "Dosage form",
  "med_form.form_placeholder": "Tablet",
  "med_form.unit": "Stock unit",
  "med_form.unit_placeholder": "pieces, ml, drops",
  "med_form.unit_default": "pieces",
  "med_form.threshold": "Low-stock warning",
  "med_form.notes": "Notes",
  "med_form.notes_placeholder": "Take with food",
  "med_form.stock_calculated": "Stock",
  "med_form.stock_calculated_help": "Calculated from all packages of this medication.",
  "med_form.package_next": "The next step adds the first package.",

  "package_form.new_title": "New package",
  "package_form.edit_title": "Edit package",
  "package_form.dialog_label": "Package",
  "package_form.step_two": "Step 2 of 2",
  "package_form.step_two_help": "Add the first physical package so stock can be tracked.",
  "package_form.medication": "Medication",
  "package_form.nickname": "Nickname",
  "package_form.nickname_help": "Left empty, a memorable name is generated.",
  "package_form.quantity": "Quantity",
  "package_form.remaining": "Remaining quantity",
  "package_form.lot": "LOT / batch",
  "package_form.expiry": "Expiry date",
  "package_form.external_code": "Printed code",
  "package_form.external_code_help": "Barcode, QR or DataMatrix content printed on the box.",
  "package_form.save": "Save package",

  "reg_form.new_title": "New plan",
  "reg_form.edit_title": "Edit plan",
  "reg_form.dialog_label": "Intake plan",
  "reg_form.name": "Name",
  "reg_form.name_placeholder": "Morning",
  "reg_form.status": "Status",
  "reg_form.medications_dose": "Medications and doses",
  "reg_form.add_medication": "Add medication",
  "reg_form.choose_medication": "Choose medication",
  "reg_form.remove": "Remove",
  "reg_form.rhythm": "Rhythm",
  "reg_form.weekly": "Weekdays",
  "reg_form.interval": "Every x days",
  "reg_form.weekdays_times": "Weekdays and times",
  "reg_form.multiple_times_help": "Several times per day separated by commas, for example 08:00, 20:00.",
  "reg_form.interval_title": "Interval",
  "reg_form.every_days": "Every x days",
  "reg_form.start_date": "Start date",
  "reg_form.time": "Time",
  "reg_form.repeat": "Repeat reminder every (min)",
  "reg_form.window": "Stop reminding after (min)",
  "reg_form.window_help": "0 keeps reminding until the intake is resolved.",
  "reg_form.auto_miss": "Mark as missed after (min)",
  "reg_form.auto_miss_help": "0 keeps the intake open indefinitely.",
  "reg_form.notify_services": "Notification services",
  "reg_form.notify_placeholder": "notify.mobile_app_phone",
  "reg_form.notify_help": "Comma separated. Action buttons need a Companion App service.",
  "reg_form.scripts": "Scripts",
  "reg_form.script_placeholder": "script.flash_lights",
  "reg_form.instructions": "Instructions",
  "reg_form.instructions_placeholder": "Take with a large glass of water",
  "reg_form.save": "Save plan",
  "reg_form.need_medication": "Create a medication first.",

  "unplanned.title": "Record intake",
  "unplanned.dialog_label": "Unplanned intake",
  "unplanned.taken_at": "Taken at",
  "unplanned.medications": "Medications and doses",
  "unplanned.note": "Note",
  "unplanned.note_placeholder": "Headache",
  "unplanned.save": "Record",
  "unplanned.history_name": "Unplanned intake",

  "code.title": "QR code for {object}",
  "code.dialog_label": "Generated scan code",
  "code.help": "The code contains only the short identifier below, no link and no medication data.",
  "code.copy": "Copy identifier",
  "code.copied": "Identifier copied.",
  "code.medication": "medication",
  "code.package": "package",
  "code.intake": "intake",
  "code.print": "Print",

  "data.title": "Backup and restore",
  "data.dialog_label": "Data management",
  "data.export_title": "Full backup",
  "data.export_help": "Downloads every medication, package, plan, ticket and retained history entry.",
  "data.export_button": "Download backup",
  "data.export_done": "Backup downloaded.",
  "data.import_title": "Restore",
  "data.import_help": "Only a compatible Medication Reminder backup is accepted.",
  "data.import_file": "Backup file",
  "data.import_warning": "Restoring replaces all current data. Download a backup first.",
  "data.import_button": "Restore backup",
  "data.import_done": "Backup restored.",

  "action.medication_saved": "Medication saved.",
  "action.medication_deleted": "Medication deleted.",
  "action.regimen_saved": "Plan saved.",
  "action.regimen_deleted": "Plan deleted.",
  "action.package_saved": "Package saved, stock recalculated.",
  "action.package_deleted": "Package deleted, stock recalculated.",
  "action.intake_recorded": "Intake recorded.",
  "action.intake_skipped": "Intake skipped.",
  "action.unplanned_saved": "Unplanned intake recorded.",
  "action.reminder_snoozed": "Reminder snoozed.",
  "action.reminder_snoozed_until": "Reminder snoozed until the chosen time.",
  "action.interval_postponed": "Intake and following interval dates moved to tomorrow.",
  "action.all_data_deleted": "All Medication Reminder data was deleted.",

  "confirm.delete_medication": "Delete this medication including all its packages?",
  "confirm.delete_regimen": "Delete this plan and its open tickets?",
  "confirm.delete_package": "Delete this package? Recorded intakes keep their package snapshot.",
  "confirm.skip": "Mark this intake as skipped without deducting stock?",
  "confirm.postpone_interval": "Move this intake to tomorrow and shift the whole interval cycle?",
  "confirm.import_backup": "Restore this backup and replace all current data?",
  "confirm.delete_all_data": "Permanently delete all medications, packages, plans, tickets and history? The integration itself stays installed.",
  "prompt.delete_all_data": "This cannot be undone. Type DELETE to confirm.",

  "error.generic": "The action failed.",
  "error.not_configured": "Medication Reminder is not set up.",
  "error.medication_in_use": "This medication is still used by a plan.",
  "error.medication_in_open_intake": "This medication is still part of an open intake.",
  "error.dose_exceeds": "The dose exceeds the remaining planned amount.",
  "error.no_dose": "No dose was selected.",
  "error.select_dose": "Select at least one dose.",
  "error.future_snooze": "The snooze time must be in the future.",
  "error.only_open_snooze": "Only open intakes can be snoozed.",
  "error.name_required": "A name is required.",
  "error.unknown_medication": "Unknown medication.",
  "error.medication_duplicate": "Each medication may only be listed once.",
  "error.medication_required": "At least one medication is required.",
  "error.select_weekday": "Select at least one weekday.",
  "error.repeat_range": "The repeat interval must be between 5 and 1440 minutes.",
  "error.window_range": "The reminder window must be between 0 and 10080 minutes.",
  "error.auto_miss_range": "The missed timeout must be between 0 and 43200 minutes.",
  "error.auto_miss_below_repeat": "The missed timeout must not be below the repeat interval.",
  "error.every_days_range": "The interval must be between 1 and 365 days.",
  "error.schedule_type": "Unsupported schedule type.",
  "error.invalid_snooze": "Invalid snooze time.",
  "error.invalid_time": "Invalid time on {day}. Use HH:MM.",
  "error.invalid_time_generic": "Invalid time. Use HH:MM.",
  "error.invalid_value": "Invalid value.",
  "error.not_enough_stock": "Not enough stock for {medication}.",
  "error.package_quantity": "The package quantity must be greater than zero.",
  "error.package_nickname": "Package nicknames must be unique per medication.",
  "error.unplanned_future": "The intake time must not be in the future.",
  "error.interval_only": "Only due, untouched interval intakes can be shifted to tomorrow.",
  "error.qr_failed": "The QR code could not be generated.",
  "error.delete_confirmation": "The confirmation did not match. No data was deleted.",
  "error.export_range": "The start date must not be after the end date.",
  "error.select_time": "Choose a time first.",
  "error.create_medication_first": "Create a medication first.",
  "error.backup_file": "Choose a backup file.",
  "error.backup_invalid": "This file is not a valid Medication Reminder backup.",
  "error.text_too_long": "The text is too long."
});

const DE = Object.freeze({
  "app.title": "Medikamente",
  "app.subtitle": "Pläne, Bestand und Einnahmeverlauf",
  "app.loading_title": "Wird geladen",
  "app.loading_text": "Lokale Daten werden aus Home Assistant gelesen.",
  "app.local_storage": "Lokal in Home Assistant gespeichert",
  "app.last_synced": "Aktualisiert {time}",
  "app.refresh": "Aktualisieren",
  "app.record_unplanned": "Einnahme erfassen",
  "app.data_management": "Sicherung und Wiederherstellung",
  "app.delete_all_data": "Alle Daten löschen",
  "app.more": "Weitere Aktionen",

  "card.name": "Medication Reminder",
  "card.description": "Fällige Einnahmen mit Erfassen, Vertagen und Auslassen.",
  "card.title_default": "Medikamente",
  "card.nothing_due": "Gerade ist nichts fällig.",
  "card.nothing_open": "Keine offenen Einnahmen.",
  "card.upcoming": "Als Nächstes",
  "card.stock": "Bestand",
  "card.not_configured": "Medication Reminder ist noch nicht eingerichtet.",
  "card.loading": "Wird geladen…",
  "card.record": "Erfassen",
  "card.more_open": "{count} weitere offen",
  "card.open_panel": "Medikamenten-Panel öffnen",
  "card.editor.title": "Titel",
  "card.editor.mode": "Anzeigen",
  "card.editor.mode_due": "Nur fällige Einnahmen",
  "card.editor.mode_open": "Alle offenen Einnahmen",
  "card.editor.max": "Maximale Anzahl Einnahmen",
  "card.editor.allow_partial": "Dosis bearbeitbar",
  "card.editor.show_snooze": "Vertagen-Buttons",
  "card.editor.show_skip": "Auslassen-Button",
  "card.editor.show_upcoming": "Kommende Einnahmen",
  "card.editor.upcoming_count": "Anzahl kommender Einnahmen",
  "card.editor.show_stock": "Bestandsübersicht",
  "card.editor.stock_filter": "Bestandseinträge",
  "card.editor.stock_all": "Alle Medikamente",
  "card.editor.stock_low": "Nur niedriger Bestand",

  "nav.overview": "Überblick",
  "nav.medications": "Medikamente",
  "nav.regimens": "Pläne",
  "nav.history": "Verlauf",

  "common.active": "Aktiv",
  "common.paused": "Pausiert",
  "common.save": "Speichern",
  "common.cancel": "Abbrechen",
  "common.edit": "Bearbeiten",
  "common.delete": "Löschen",
  "common.details": "Details",
  "common.none": "Keine",
  "common.close": "Schließen",
  "common.minutes_short": "Min.",
  "common.days_short": "T",
  "common.optional": "optional",
  "common.advanced": "Erweitert",
  "common.all": "Alle",
  "common.search": "Suchen",

  "status.pending": "Offen",
  "status.partial": "Teilweise",
  "status.taken": "Genommen",
  "status.skipped": "Ausgelassen",
  "status.missed": "Versäumt",

  "day.monday": "Montag",
  "day.tuesday": "Dienstag",
  "day.wednesday": "Mittwoch",
  "day.thursday": "Donnerstag",
  "day.friday": "Freitag",
  "day.saturday": "Samstag",
  "day.sunday": "Sonntag",
  "day.short.monday": "Mo",
  "day.short.tuesday": "Di",
  "day.short.wednesday": "Mi",
  "day.short.thursday": "Do",
  "day.short.friday": "Fr",
  "day.short.saturday": "Sa",
  "day.short.sunday": "So",

  "relative.now": "jetzt",
  "relative.before_minutes": "vor {minutes} Min.",
  "relative.in_minutes": "in {minutes} Min.",
  "relative.before_hours": "vor {hours} Std.",
  "relative.in_hours": "in {hours} Std.",
  "relative.before_days": "vor {days} T.",
  "relative.in_days": "in {days} T.",

  "overview.due_now": "Jetzt fällig",
  "overview.due_later": "Später geplant",
  "overview.upcoming": "Als Nächstes",
  "overview.no_due_title": "Gerade ist nichts einzunehmen",
  "overview.no_due_text": "Offene Einnahmen erscheinen hier, sobald sie fällig sind.",
  "overview.no_upcoming": "Kein aktiver Plan hat einen nächsten Termin.",
  "overview.warnings": "Braucht Aufmerksamkeit",
  "overview.metric_open": "Offene Einnahmen",
  "overview.metric_due": "Jetzt fällig",
  "overview.metric_adherence": "Therapietreue {days} T.",
  "overview.metric_low": "Bestand niedrig",
  "overview.no_medications_title": "Noch keine Medikamente",
  "overview.no_medications_text": "Lege ein Medikament und seine erste Packung an.",
  "overview.add_medication": "Medikament anlegen",
  "overview.low_stock_warning": "{name}: noch {stock} {unit} (Warnung ab {threshold})",
  "overview.expiry_warning": "{name}: Packung {package} läuft am {date} ab",
  "overview.expired_warning": "{name}: Packung {package} ist am {date} abgelaufen",
  "overview.no_warnings": "Keine Warnungen.",

  "ticket.due": "Geplant {time}",
  "ticket.snoozed_until": "vertagt bis {time}",
  "ticket.take_selection": "Auswahl erfassen",
  "ticket.take_all": "Alles erfassen",
  "ticket.snooze": "Vertagen",
  "ticket.snooze_30": "30 Min.",
  "ticket.snooze_60": "1 Std.",
  "ticket.snooze_120": "2 Std.",
  "ticket.custom_snooze": "Auf gewählte Zeit vertagen",
  "ticket.postpone_tomorrow": "Zyklus auf morgen",
  "ticket.skip": "Auslassen",
  "ticket.qr": "Einnahme-QR-Code",
  "ticket.already_taken": "{amount} bereits genommen",
  "ticket.take_from": "Entnehmen aus {packages}",
  "ticket.deleted_medication": "Gelöschtes Medikament",
  "ticket.unplanned": "Ungeplante Einnahme",
  "ticket.orphan_plan": "Plan existiert nicht mehr",
  "ticket.overdue": "Überfällig",
  "ticket.ad_hoc": "Einmalig",
  "ticket.reason": "Grund: {reason}",

  "medications.title": "Medikamente",
  "medications.subtitle": "Stammdaten, Packungen und daraus berechneter Bestand.",
  "medications.create": "Neues Medikament",
  "medications.empty_title": "Keine Medikamente",
  "medications.empty_text": "Lege ein Medikament an und ergänze dann Packungen.",

  "stock.available": "Vorrätig",
  "stock.reorder": "Nachbestellen",
  "stock.empty": "Leer",
  "stock.no_details": "Keine weiteren Angaben",
  "stock.warning_at": "Warnung ab {amount} {unit}",
  "stock.supply": "reicht ca. {days} T.",
  "stock.supply_unknown": "kein aktiver Plan",
  "stock.packages": "Packungen",
  "stock.no_packages": "Noch keine Packungen.",
  "stock.add_package": "Packung hinzufügen",
  "stock.next_package": "Nächste: {package}",

  "package.remaining": "{amount} von {initial} {unit} übrig",
  "package.lot": "LOT {lot}",
  "package.expires": "MHD {date}",
  "package.expired": "abgelaufen am {date}",
  "package.no_expiry": "kein Ablaufdatum",
  "package.code": "QR-Code",
  "package.edit": "Packung bearbeiten",
  "package.delete": "Packung löschen",

  "regimens.title": "Einnahmepläne",
  "regimens.subtitle": "Wann welches Medikament fällig ist und wer benachrichtigt wird.",
  "regimens.create": "Neuer Plan",
  "regimens.empty_title": "Keine Pläne",
  "regimens.empty_text": "Ein Plan legt Zeiten, Dosen und Erinnerungen fest.",
  "schedule.every_day": "Täglich um {time}, ab {date}",
  "schedule.every_days": "Alle {days} Tage um {time}, ab {date}",
  "schedule.weekly_group": "{days} · {times}",
  "regimens.next": "Nächster Termin: {time}",
  "regimens.no_next": "Kein kommender Termin",
  "regimens.reminder_summary": "{targets} Benachrichtigungsziele · Wiederholung alle {minutes} Min.",
  "regimens.reminder_none": "Kein Benachrichtigungsziel · nur im Panel",
  "regimens.window": "Erinnerungen enden {minutes} Min. nach Fälligkeit",
  "regimens.auto_miss": "gilt nach {minutes} Min. als versäumt",

  "history.title": "Verlauf",
  "history.subtitle": "Geplante gegen tatsächliche Einnahme, inklusive Packungschargen.",
  "history.export_title": "Zeitraum exportieren",
  "history.export_help": "Exportiert werden nur erledigte, ausgelassene und versäumte Einträge.",
  "history.export_from": "Von",
  "history.export_to": "Bis",
  "history.export_json": "JSON",
  "history.export_csv": "CSV",
  "history.export_done": "{count} Einträge exportiert.",
  "history.export_empty": "Keine Einträge in diesem Zeitraum.",
  "history.status": "Status",
  "history.intake": "Einnahme",
  "history.scheduled": "Geplant",
  "history.actual": "Tatsächlich",
  "history.deviation": "Abweichung",
  "history.doses": "Dosen",
  "history.packages": "Packungen: {packages}",
  "history.deleted_schedule": "Gelöschter Plan",
  "history.empty_title": "Noch kein Verlauf",
  "history.empty_text": "Erfasste und ausgelassene Einnahmen erscheinen hier.",
  "history.filter_status": "Status",
  "history.filter_search": "Nach Medikament oder Plan filtern",
  "history.adherence": "Therapietreue über {days} Tage: {rate} % von {total} geplanten Einnahmen",
  "history.adherence_none": "Noch zu wenige geplante Einnahmen für einen Wert.",
  "history.counts": "{taken} genommen · {partial} teilweise · {skipped} ausgelassen · {missed} versäumt",

  "med_form.new_title": "Neues Medikament",
  "med_form.edit_title": "Medikament bearbeiten",
  "med_form.dialog_label": "Medikament",
  "med_form.name": "Name",
  "med_form.name_placeholder": "Ibuprofen",
  "med_form.manufacturer": "Hersteller",
  "med_form.manufacturer_placeholder": "Ratiopharm",
  "med_form.barcode": "Barcode / Produktcode",
  "med_form.barcode_placeholder": "PZN oder EAN",
  "med_form.strength": "Stärke",
  "med_form.strength_placeholder": "400 mg",
  "med_form.form": "Darreichungsform",
  "med_form.form_placeholder": "Tablette",
  "med_form.unit": "Bestandseinheit",
  "med_form.unit_placeholder": "Stück, ml, Tropfen",
  "med_form.unit_default": "Stück",
  "med_form.threshold": "Warnung bei Bestand",
  "med_form.notes": "Notizen",
  "med_form.notes_placeholder": "Zum Essen einnehmen",
  "med_form.stock_calculated": "Bestand",
  "med_form.stock_calculated_help": "Wird aus allen Packungen dieses Medikaments berechnet.",
  "med_form.package_next": "Im nächsten Schritt wird die erste Packung angelegt.",

  "package_form.new_title": "Neue Packung",
  "package_form.edit_title": "Packung bearbeiten",
  "package_form.dialog_label": "Packung",
  "package_form.step_two": "Schritt 2 von 2",
  "package_form.step_two_help": "Lege die erste physische Packung an, damit der Bestand stimmt.",
  "package_form.medication": "Medikament",
  "package_form.nickname": "Spitzname",
  "package_form.nickname_help": "Leer lassen erzeugt automatisch einen merkbaren Namen.",
  "package_form.quantity": "Menge",
  "package_form.remaining": "Restmenge",
  "package_form.lot": "LOT / Charge",
  "package_form.expiry": "Ablaufdatum",
  "package_form.external_code": "Aufgedruckter Code",
  "package_form.external_code_help": "Barcode-, QR- oder DataMatrix-Inhalt von der Packung.",
  "package_form.save": "Packung speichern",

  "reg_form.new_title": "Neuer Plan",
  "reg_form.edit_title": "Plan bearbeiten",
  "reg_form.dialog_label": "Einnahmeplan",
  "reg_form.name": "Name",
  "reg_form.name_placeholder": "Morgens",
  "reg_form.status": "Status",
  "reg_form.medications_dose": "Medikamente und Dosen",
  "reg_form.add_medication": "Medikament hinzufügen",
  "reg_form.choose_medication": "Medikament wählen",
  "reg_form.remove": "Entfernen",
  "reg_form.rhythm": "Rhythmus",
  "reg_form.weekly": "Wochentage",
  "reg_form.interval": "Alle x Tage",
  "reg_form.weekdays_times": "Wochentage und Zeiten",
  "reg_form.multiple_times_help": "Mehrere Zeiten pro Tag mit Komma trennen, zum Beispiel 08:00, 20:00.",
  "reg_form.interval_title": "Intervall",
  "reg_form.every_days": "Alle x Tage",
  "reg_form.start_date": "Startdatum",
  "reg_form.time": "Uhrzeit",
  "reg_form.repeat": "Erinnerung wiederholen alle (Min.)",
  "reg_form.window": "Erinnern beenden nach (Min.)",
  "reg_form.window_help": "0 erinnert, bis die Einnahme erledigt ist.",
  "reg_form.auto_miss": "Als versäumt markieren nach (Min.)",
  "reg_form.auto_miss_help": "0 lässt die Einnahme dauerhaft offen.",
  "reg_form.notify_services": "Benachrichtigungsdienste",
  "reg_form.notify_placeholder": "notify.mobile_app_handy",
  "reg_form.notify_help": "Mit Komma trennen. Aktionsknöpfe brauchen einen Companion-App-Dienst.",
  "reg_form.scripts": "Skripte",
  "reg_form.script_placeholder": "script.licht_blinken",
  "reg_form.instructions": "Hinweise",
  "reg_form.instructions_placeholder": "Mit einem großen Glas Wasser einnehmen",
  "reg_form.save": "Plan speichern",
  "reg_form.need_medication": "Lege zuerst ein Medikament an.",

  "unplanned.title": "Einnahme erfassen",
  "unplanned.dialog_label": "Ungeplante Einnahme",
  "unplanned.taken_at": "Eingenommen am",
  "unplanned.medications": "Medikamente und Dosen",
  "unplanned.note": "Notiz",
  "unplanned.note_placeholder": "Kopfschmerzen",
  "unplanned.save": "Erfassen",
  "unplanned.history_name": "Ungeplante Einnahme",

  "code.title": "QR-Code für {object}",
  "code.dialog_label": "Generierter Scan-Code",
  "code.help": "Der Code enthält nur die kurze Kennung unten, keinen Link und keine Medikamentendaten.",
  "code.copy": "Kennung kopieren",
  "code.copied": "Kennung kopiert.",
  "code.medication": "Medikament",
  "code.package": "Packung",
  "code.intake": "Einnahme",
  "code.print": "Drucken",

  "data.title": "Sicherung und Wiederherstellung",
  "data.dialog_label": "Datenverwaltung",
  "data.export_title": "Vollständige Sicherung",
  "data.export_help": "Lädt alle Medikamente, Packungen, Pläne, Tickets und den gespeicherten Verlauf herunter.",
  "data.export_button": "Sicherung herunterladen",
  "data.export_done": "Sicherung heruntergeladen.",
  "data.import_title": "Wiederherstellen",
  "data.import_help": "Es wird nur eine kompatible Medication-Reminder-Sicherung akzeptiert.",
  "data.import_file": "Sicherungsdatei",
  "data.import_warning": "Die Wiederherstellung ersetzt alle aktuellen Daten. Lade vorher eine Sicherung herunter.",
  "data.import_button": "Sicherung einspielen",
  "data.import_done": "Sicherung wiederhergestellt.",

  "action.medication_saved": "Medikament gespeichert.",
  "action.medication_deleted": "Medikament gelöscht.",
  "action.regimen_saved": "Plan gespeichert.",
  "action.regimen_deleted": "Plan gelöscht.",
  "action.package_saved": "Packung gespeichert, Bestand neu berechnet.",
  "action.package_deleted": "Packung gelöscht, Bestand neu berechnet.",
  "action.intake_recorded": "Einnahme erfasst.",
  "action.intake_skipped": "Einnahme ausgelassen.",
  "action.unplanned_saved": "Ungeplante Einnahme erfasst.",
  "action.reminder_snoozed": "Erinnerung vertagt.",
  "action.reminder_snoozed_until": "Erinnerung bis zur gewählten Zeit vertagt.",
  "action.interval_postponed": "Einnahme und folgende Intervalltermine auf morgen verschoben.",
  "action.all_data_deleted": "Alle Medication-Reminder-Daten wurden gelöscht.",

  "confirm.delete_medication": "Dieses Medikament samt aller Packungen löschen?",
  "confirm.delete_regimen": "Diesen Plan und seine offenen Tickets löschen?",
  "confirm.delete_package": "Diese Packung löschen? Erfasste Einnahmen behalten ihren Packungs-Snapshot.",
  "confirm.skip": "Diese Einnahme ohne Bestandsabbuchung als ausgelassen markieren?",
  "confirm.postpone_interval": "Diese Einnahme auf morgen und den gesamten Intervallzyklus verschieben?",
  "confirm.import_backup": "Diese Sicherung einspielen und alle aktuellen Daten ersetzen?",
  "confirm.delete_all_data": "Alle Medikamente, Packungen, Pläne, Tickets und den Verlauf dauerhaft löschen? Die Integration bleibt installiert.",
  "prompt.delete_all_data": "Das kann nicht rückgängig gemacht werden. Zur Bestätigung DELETE eingeben.",

  "error.generic": "Die Aktion ist fehlgeschlagen.",
  "error.not_configured": "Medication Reminder ist nicht eingerichtet.",
  "error.medication_in_use": "Dieses Medikament wird noch von einem Plan verwendet.",
  "error.medication_in_open_intake": "Dieses Medikament gehört noch zu einer offenen Einnahme.",
  "error.dose_exceeds": "Die Dosis übersteigt die verbleibende geplante Menge.",
  "error.no_dose": "Es wurde keine Dosis ausgewählt.",
  "error.select_dose": "Wähle mindestens eine Dosis aus.",
  "error.future_snooze": "Die Vertagung muss in der Zukunft liegen.",
  "error.only_open_snooze": "Nur offene Einnahmen können vertagt werden.",
  "error.name_required": "Ein Name ist erforderlich.",
  "error.unknown_medication": "Unbekanntes Medikament.",
  "error.medication_duplicate": "Jedes Medikament darf nur einmal vorkommen.",
  "error.medication_required": "Mindestens ein Medikament ist erforderlich.",
  "error.select_weekday": "Wähle mindestens einen Wochentag.",
  "error.repeat_range": "Die Wiederholung muss zwischen 5 und 1440 Minuten liegen.",
  "error.window_range": "Das Erinnerungsfenster muss zwischen 0 und 10080 Minuten liegen.",
  "error.auto_miss_range": "Die Versäumt-Frist muss zwischen 0 und 43200 Minuten liegen.",
  "error.auto_miss_below_repeat": "Die Versäumt-Frist darf nicht unter der Wiederholung liegen.",
  "error.every_days_range": "Das Intervall muss zwischen 1 und 365 Tagen liegen.",
  "error.schedule_type": "Nicht unterstützter Zeitplantyp.",
  "error.invalid_snooze": "Ungültige Vertagungszeit.",
  "error.invalid_time": "Ungültige Zeit am {day}. Format HH:MM.",
  "error.invalid_time_generic": "Ungültige Zeit. Format HH:MM.",
  "error.invalid_value": "Ungültiger Wert.",
  "error.not_enough_stock": "Nicht genug Bestand für {medication}.",
  "error.package_quantity": "Die Packungsmenge muss größer als null sein.",
  "error.package_nickname": "Packungs-Spitznamen müssen pro Medikament eindeutig sein.",
  "error.unplanned_future": "Die Einnahmezeit darf nicht in der Zukunft liegen.",
  "error.interval_only": "Nur fällige, unberührte Intervall-Einnahmen können auf morgen verschoben werden.",
  "error.qr_failed": "Der QR-Code konnte nicht erzeugt werden.",
  "error.delete_confirmation": "Die Bestätigung stimmt nicht. Es wurden keine Daten gelöscht.",
  "error.export_range": "Das Startdatum darf nicht nach dem Enddatum liegen.",
  "error.select_time": "Wähle zuerst eine Zeit.",
  "error.create_medication_first": "Lege zuerst ein Medikament an.",
  "error.backup_file": "Wähle eine Sicherungsdatei.",
  "error.backup_invalid": "Diese Datei ist keine gültige Medication-Reminder-Sicherung.",
  "error.text_too_long": "Der Text ist zu lang."
});

export const CATALOGS = Object.freeze({ en: EN, de: DE });

export function resolveLanguage(hass) {
  const requested = String(hass?.language || hass?.locale?.language || "en")
    .toLowerCase().split("-")[0];
  return Object.hasOwn(CATALOGS, requested) ? requested : "en";
}

export function createTranslator(language) {
  const catalog = CATALOGS[language] || EN;
  return (key, variables = {}) => {
    const template = catalog[key] ?? EN[key] ?? key;
    return template.replace(/\{(\w+)\}/g, (_match, name) =>
      String(variables[name] ?? `{${name}}`));
  };
}
