const EN = Object.freeze({
  "app.title": "My medication schedule",
  "app.loading_title": "Loading medication schedule",
  "app.loading_text": "Reading local data securely from Home Assistant.",
  "app.local_storage": "Stored locally in Home Assistant",
  "app.last_synced": "Last synced {time}",
  "app.refresh": "Refresh",
  "nav.overview": "Overview",
  "nav.medications": "Medications",
  "nav.regimens": "Intakes",
  "nav.history": "History",
  "common.active": "Active",
  "common.paused": "Paused",
  "common.save": "Save",
  "common.cancel": "Cancel",
  "common.edit": "Edit",
  "common.delete": "Delete",
  "common.details": "Details",
  "common.none": "None",
  "common.minutes_short": "min",
  "common.close": "Close",
  "common.hours_short": "hr",
  "status.pending": "Pending",
  "status.partial": "Partial",
  "status.taken": "Taken",
  "status.skipped": "Skipped",
  "day.monday": "Monday",
  "day.tuesday": "Tuesday",
  "day.wednesday": "Wednesday",
  "day.thursday": "Thursday",
  "day.friday": "Friday",
  "day.saturday": "Saturday",
  "day.sunday": "Sunday",
  "relative.now": "now",
  "relative.before_minutes": "{minutes} min ago",
  "relative.in_minutes": "in {minutes} min",
  "relative.before_hours": "{hours} hr ago",
  "relative.in_hours": "in {hours} hr",
  "overview.eyebrow": "TODAY AT A GLANCE",
  "overview.waiting_one": "1 intake is waiting",
  "overview.waiting_many": "{count} intakes are waiting",
  "overview.all_done": "Everything is done",
  "overview.open_help": "Record the amounts actually taken or postpone the reminder.",
  "overview.no_open": "There are currently no open intakes.",
  "overview.next_intake": "Next intake",
  "overview.open_tickets": "Open tickets",
  "overview.check_required": "Please review",
  "overview.up_to_date": "Everything up to date",
  "overview.low_stock": "Low stock",
  "overview.well_stocked": "Well stocked",
  "overview.medications": "Medications",
  "overview.active_plans": "{count} active schedules",
  "overview.open_eyebrow": "OPEN TICKETS",
  "overview.due_intakes": "Due intakes",
  "overview.no_due_title": "No open intakes",
  "overview.no_due_text": "A ticket will appear here as soon as an intake becomes due.",
  "overview.stock_eyebrow": "STOCK",
  "overview.quick_view": "Quick overview",
  "overview.add_medication": "Medication",
  "overview.no_medications_title": "No medications yet",
  "overview.no_medications_text": "Create a medication first.",
  "ticket.due": "Due: {time}",
  "ticket.snoozed_until": "Snoozed until {time}",
  "ticket.deleted_medication": "Deleted medication",
  "ticket.already_taken": "{amount} already taken",
  "ticket.take_selection": "Mark selection taken",
  "ticket.snooze_30": "30 min",
  "ticket.snooze_60": "1 hr",
  "ticket.snooze_120": "2 hr",
  "ticket.custom_snooze": "Snooze until the selected time",
  "ticket.skip": "Skip",
  "medications.eyebrow": "MEDICINE CABINET",
  "medications.title": "Medications & stock",
  "medications.subtitle": "Manage package data, dose units and warning thresholds in one place.",
  "medications.create": "Create medication",
  "medications.empty_title": "No medications yet",
  "medications.empty_text": "Create your first medication, then add its first physical package.",
  "stock.reorder": "Reorder",
  "stock.available": "Available",
  "stock.no_details": "No additional details",
  "stock.warning_at": "Warning at {amount} {unit}",
  "regimens.eyebrow": "SCHEDULES",
  "regimens.title": "Intakes & reminders",
  "regimens.subtitle": "Flexible weekly and interval schedules with individual notification targets.",
  "regimens.create": "Schedule intake",
  "regimens.empty_title": "No intakes scheduled",
  "regimens.empty_text": "Create a weekly schedule or an every-x-days interval.",
  "regimens.reminder_summary": "{targets} notification target(s) · repeats every {minutes} min",
  "schedule.every_day": "Every day, starting {date} at {time}",
  "schedule.every_days": "Every {days} days, starting {date} at {time}",
  "schedule.weekly_group": "{days} · {times}",
  "history.eyebrow": "LOG",
  "history.title": "Intake history",
  "history.subtitle": "Scheduled and actual time together with the doses deducted from stock.",
  "history.status": "Status",
  "history.intake": "Intake",
  "history.scheduled": "Scheduled",
  "history.actual": "Actual",
  "history.deviation": "Deviation",
  "history.doses": "Doses",
  "history.deleted_schedule": "Deleted schedule",
  "history.empty_title": "No history yet",
  "history.empty_text": "Completed and skipped intakes are logged here.",
  "history.export_title": "Export intake history",
  "history.export_help": "Exports retained completed and skipped intakes in the inclusive date range.",
  "history.export_from": "From",
  "history.export_to": "To",
  "history.export_json": "JSON",
  "history.export_csv": "CSV",
  "history.export_empty": "There are no completed or skipped intakes in this period.",
  "history.export_done": "Exported {count} intake record(s).",
  "med_form.eyebrow": "MEDICATION",
  "med_form.edit_title": "Edit medication",
  "med_form.new_title": "New medication",
  "med_form.dialog_label": "Edit medication",
  "med_form.name": "Name",
  "med_form.name_placeholder": "e.g. Metformin",
  "med_form.manufacturer": "Manufacturer",
  "med_form.manufacturer_placeholder": "e.g. 1A Pharma",
  "med_form.barcode": "Barcode / product code",
  "med_form.barcode_placeholder": "Scan or product number",
  "med_form.strength": "Strength",
  "med_form.strength_placeholder": "e.g. 500 mg",
  "med_form.form": "Dosage form",
  "med_form.form_placeholder": "Tablet, drops, …",
  "med_form.unit": "Stock unit",
  "med_form.unit_default": "pieces",
  "med_form.unit_placeholder": "pieces, ml, sprays, …",
  "med_form.stock_calculated": "Calculated stock",
  "med_form.stock_calculated_help": "Always calculated from the remaining quantities in all packages.",
  "med_form.package_next": "After saving, add the first physical package in step 2.",
  "med_form.threshold": "Warning threshold",
  "med_form.notes": "Notes",
  "med_form.notes_placeholder": "Optional notes",
  "reg_form.eyebrow": "INTAKE SCHEDULE",
  "reg_form.edit_title": "Edit intake",
  "reg_form.new_title": "New intake",
  "reg_form.dialog_label": "Edit intake",
  "reg_form.name": "Name",
  "reg_form.name_placeholder": "e.g. Lunchtime medication",
  "reg_form.status": "Status",
  "reg_form.medications_dose": "Medications & dose",
  "reg_form.add_medication": "Add another medication",
  "reg_form.rhythm": "Schedule type",
  "reg_form.weekly": "Weekly by weekday",
  "reg_form.interval": "Every x days",
  "reg_form.repeat": "Remind again after (minutes)",
  "reg_form.weekdays_times": "Weekdays and times",
  "reg_form.multiple_times_help": "Separate multiple times with commas.",
  "reg_form.interval_title": "Interval",
  "reg_form.every_days": "Every x days",
  "reg_form.start_date": "Start date",
  "reg_form.time": "Time",
  "reg_form.notify_services": "Notification services",
  "reg_form.notify_placeholder": "notify.mobile_app_my_phone",
  "reg_form.notify_help": "Separate multiple services with commas. Action buttons are added automatically.",
  "reg_form.scripts": "Scripts for every reminder",
  "reg_form.script_placeholder": "script.medication_reminder",
  "reg_form.instructions": "Intake instructions",
  "reg_form.instructions_placeholder": "e.g. Take with a glass of water and food",
  "reg_form.save": "Save schedule",
  "reg_form.choose_medication": "Choose medication",
  "reg_form.remove": "Remove",
  "action.medication_deleted": "Medication deleted.",
  "action.regimen_deleted": "Intake schedule deleted.",
  "action.reminder_snoozed": "Reminder postponed.",
  "action.reminder_snoozed_until": "Reminder postponed until the selected time.",
  "action.intake_skipped": "Intake marked as skipped.",
  "action.intake_recorded": "Intake saved and stock deducted.",
  "action.medication_saved": "Medication saved.",
  "action.regimen_saved": "Intake schedule saved.",
  "confirm.delete_medication": "Delete this medication?",
  "confirm.delete_regimen": "Delete this intake schedule? Open tickets will also be removed.",
  "confirm.skip": "Skip this intake? Stock will not be changed.",
  "error.generic": "The action could not be completed.",
  "error.create_medication_first": "Create at least one medication first.",
  "error.select_time": "Select a time first.",
  "error.future_snooze": "The snooze time must be in the future.",
  "error.select_dose": "Select at least one dose.",
  "error.duplicate_medication": "A medication may only occur once per schedule.",
  "error.invalid_time": "Invalid time for {day}.",
  "error.select_weekday": "Select at least one weekday.",
  "error.not_configured": "Medication Reminder is not configured.",
  "error.medication_in_use": "This medication is still used by an intake schedule.",
  "error.dose_exceeds": "The taken dose exceeds the remaining planned dose.",
  "error.not_enough_stock": "Not enough stock for {medication}.",
  "error.no_dose": "No dose was selected.",
  "error.only_open_snooze": "Only open intakes can be snoozed.",
  "error.name_required": "A name is required.",
  "error.unknown_medication": "The selected medication no longer exists.",
  "error.medication_duplicate": "A medication may only occur once per schedule.",
  "error.medication_required": "At least one medication is required.",
  "error.repeat_range": "The reminder interval must be between 5 and 1440 minutes.",
  "error.every_days_range": "The day interval must be between 1 and 365.",
  "error.schedule_type": "This schedule type is not supported.",
  "error.invalid_snooze": "The snooze time is invalid.",
  "error.invalid_time_generic": "One of the entered times is invalid.",
  "error.invalid_value": "One of the entered values is invalid.",
  "error.export_range": "Select a valid date range. The start date must not be after the end date.",
  "app.record_unplanned": "Unplanned intake",
  "app.delete_all_data": "Delete all Medication Reminder data",
  "app.data_management": "Backup and restore",
  "data.eyebrow": "DATA MANAGEMENT",
  "data.title": "Backup and restore",
  "data.dialog_label": "Manage Medication Reminder data",
  "data.export_title": "Download full backup",
  "data.export_help": "Exports medications, packages, schedules, open tickets, and complete retained history as JSON.",
  "data.export_button": "Download backup",
  "data.export_done": "Full backup downloaded.",
  "data.import_title": "Restore full backup",
  "data.import_help": "Select a Medication Reminder JSON backup created by this integration.",
  "data.import_file": "Backup file",
  "data.import_warning": "Import replaces all current Medication Reminder data. Export the current state first if you may need it.",
  "data.import_button": "Import and replace",
  "data.import_done": "Backup imported successfully.",
  "confirm.import_backup": "Replace all current Medication Reminder data with this backup? This cannot be undone unless you exported the current data first.",
  "error.backup_file": "Select a JSON backup file first.",
  "error.backup_invalid": "The backup could not be imported. It is invalid, damaged, or from an unsupported version.",
  "stock.automatic": "Automatic from packages",
  "stock.packages": "Packages",
  "stock.add_package": "Add package",
  "stock.no_packages": "No packages yet",
  "stock.next_package": "Use {package} first",
  "package.remaining": "{amount} {unit} remaining",
  "package.initial": "Initially {amount} {unit}",
  "package.lot": "LOT {lot}",
  "package.expires": "Expires {date}",
  "package.no_expiry": "No expiry date",
  "package.edit": "Edit package",
  "package.delete": "Delete package",
  "package.code": "QR code",
  "package_form.eyebrow": "PHYSICAL PACKAGE",
  "package_form.new_title": "Add package",
  "package_form.edit_title": "Edit package",
  "package_form.dialog_label": "Edit physical package",
  "package_form.medication": "Medication",
  "package_form.nickname": "Nickname",
  "package_form.nickname_help": "Leave empty to choose a fun unused name automatically.",
  "package_form.quantity": "Quantity",
  "package_form.remaining": "Remaining quantity",
  "package_form.lot": "LOT / batch number",
  "package_form.expiry": "Expiry date",
  "package_form.external_code": "Printed barcode / QR / DataMatrix content",
  "package_form.external_code_help": "Optional original code printed by the manufacturer.",
  "package_form.save": "Save package",
  "package_form.step_two": "Step 2 of 2 · Add the first package",
  "package_form.step_two_help": "The medication is saved. Its stock starts at zero and increases when you save this package.",
  "unplanned.eyebrow": "UNPLANNED INTAKE",
  "unplanned.title": "Record medication taken now",
  "unplanned.dialog_label": "Record unplanned intake",
  "unplanned.taken_at": "Taken at",
  "unplanned.medications": "Medications & actual doses",
  "unplanned.save": "Record intake",
  "unplanned.history_name": "Unplanned intake",
  "ticket.take_from": "Take from {packages}",
  "ticket.postpone_tomorrow": "Move cycle to tomorrow",
  "ticket.qr": "Intake QR code",
  "history.packages": "Packages: {packages}",
  "code.eyebrow": "SCAN CODE",
  "code.title": "{object} QR code",
  "code.dialog_label": "Generated scan code",
  "code.help": "This QR code contains only the short identifier below. It does not contain a link or any medication data.",
  "code.copy": "Copy identifier",
  "code.copied": "Short identifier copied.",
  "code.medication": "Medication",
  "code.package": "Package",
  "code.intake": "Intake",
  "action.package_saved": "Package saved and stock recalculated.",
  "action.package_deleted": "Package deleted and stock recalculated.",
  "action.unplanned_saved": "Unplanned intake recorded and stock deducted.",
  "action.interval_postponed": "Intake and following interval dates moved to tomorrow.",
  "action.all_data_deleted": "All Medication Reminder data was deleted.",
  "confirm.delete_package": "Delete this package? Existing intake history keeps its package snapshot.",
  "confirm.postpone_interval": "Move this intake to tomorrow and shift the complete interval cycle?",
  "confirm.delete_all_data": "Permanently delete all medications, packages, schedules, tickets, and history? The integration itself stays installed.",
  "prompt.delete_all_data": "This cannot be undone. Enter DELETE to confirm.",
  "error.package_quantity": "Package quantity must be greater than zero.",
  "error.package_nickname": "Package nicknames must be unique per medication.",
  "error.unplanned_future": "The intake time must not be in the future.",
  "error.interval_only": "Only due, untouched interval intakes can shift to tomorrow.",
  "error.qr_failed": "The QR code could not be generated.",
  "error.delete_confirmation": "The confirmation did not match. No data was deleted."
});

const DE = Object.freeze({
  "app.title": "Mein Medikamentenplan",
  "app.loading_title": "Medikamentenplan wird geladen",
  "app.loading_text": "Lokale Daten werden sicher aus Home Assistant gelesen.",
  "app.local_storage": "Lokal in Home Assistant gespeichert",
  "app.last_synced": "Zuletzt synchronisiert {time}",
  "app.refresh": "Aktualisieren",
  "nav.overview": "Übersicht",
  "nav.medications": "Medikamente",
  "nav.regimens": "Einnahmen",
  "nav.history": "Verlauf",
  "common.active": "Aktiv",
  "common.paused": "Pausiert",
  "common.save": "Speichern",
  "common.cancel": "Abbrechen",
  "common.edit": "Bearbeiten",
  "common.delete": "Löschen",
  "common.details": "Details",
  "common.none": "Keine",
  "common.minutes_short": "Min.",
  "common.close": "Schließen",
  "common.hours_short": "Std.",
  "status.pending": "Offen",
  "status.partial": "Teilweise",
  "status.taken": "Genommen",
  "status.skipped": "Ausgelassen",
  "day.monday": "Montag",
  "day.tuesday": "Dienstag",
  "day.wednesday": "Mittwoch",
  "day.thursday": "Donnerstag",
  "day.friday": "Freitag",
  "day.saturday": "Samstag",
  "day.sunday": "Sonntag",
  "relative.now": "jetzt",
  "relative.before_minutes": "vor {minutes} Min.",
  "relative.in_minutes": "in {minutes} Min.",
  "relative.before_hours": "vor {hours} Std.",
  "relative.in_hours": "in {hours} Std.",
  "overview.eyebrow": "HEUTE IM BLICK",
  "overview.waiting_one": "1 Einnahme wartet",
  "overview.waiting_many": "{count} Einnahmen warten",
  "overview.all_done": "Alles erledigt",
  "overview.open_help": "Erfasse die tatsächlich genommenen Mengen oder verschiebe die Erinnerung.",
  "overview.no_open": "Aktuell sind keine Einnahmen offen.",
  "overview.next_intake": "Nächste Einnahme",
  "overview.open_tickets": "Offene Vorgänge",
  "overview.check_required": "Bitte prüfen",
  "overview.up_to_date": "Alles aktuell",
  "overview.low_stock": "Niedriger Bestand",
  "overview.well_stocked": "Gut versorgt",
  "overview.medications": "Medikamente",
  "overview.active_plans": "{count} aktive Pläne",
  "overview.open_eyebrow": "OFFENE TICKETS",
  "overview.due_intakes": "Fällige Einnahmen",
  "overview.no_due_title": "Keine offenen Einnahmen",
  "overview.no_due_text": "Sobald eine Einnahme fällig wird, erscheint sie hier.",
  "overview.stock_eyebrow": "BESTÄNDE",
  "overview.quick_view": "Schneller Überblick",
  "overview.add_medication": "Medikament",
  "overview.no_medications_title": "Noch keine Medikamente",
  "overview.no_medications_text": "Lege zuerst ein Medikament an.",
  "ticket.due": "Soll: {time}",
  "ticket.snoozed_until": "Schlummert bis {time}",
  "ticket.deleted_medication": "Gelöschtes Medikament",
  "ticket.already_taken": "{amount} bereits genommen",
  "ticket.take_selection": "Auswahl genommen",
  "ticket.snooze_30": "30 Min.",
  "ticket.snooze_60": "1 Std.",
  "ticket.snooze_120": "2 Std.",
  "ticket.custom_snooze": "Bis zur gewählten Zeit schlummern",
  "ticket.skip": "Auslassen",
  "medications.eyebrow": "APOTHEKE",
  "medications.title": "Medikamente & Bestände",
  "medications.subtitle": "Packungsdaten, Dosiseinheit und Warnschwellen zentral verwalten.",
  "medications.create": "Medikament anlegen",
  "medications.empty_title": "Noch keine Medikamente",
  "medications.empty_text": "Erstelle dein erstes Medikament und füge danach die erste physische Packung hinzu.",
  "stock.reorder": "Nachbestellen",
  "stock.available": "Verfügbar",
  "stock.no_details": "Keine Zusatzangaben",
  "stock.warning_at": "Warnung ab {amount} {unit}",
  "regimens.eyebrow": "ZEITPLÄNE",
  "regimens.title": "Einnahmen & Erinnerungen",
  "regimens.subtitle": "Flexible Wochen- und Intervallpläne mit eigenen Benachrichtigungszielen.",
  "regimens.create": "Einnahme planen",
  "regimens.empty_title": "Noch keine Einnahmen geplant",
  "regimens.empty_text": "Erstelle einen Wochenplan oder einen Rhythmus alle x Tage.",
  "regimens.reminder_summary": "{targets} Benachrichtigungsziel(e) · Wiederholung alle {minutes} Min.",
  "schedule.every_day": "Jeden Tag, ab {date} um {time}",
  "schedule.every_days": "Alle {days} Tage, ab {date} um {time}",
  "schedule.weekly_group": "{days} · {times}",
  "history.eyebrow": "PROTOKOLL",
  "history.title": "Einnahmeverlauf",
  "history.subtitle": "Soll- und Ist-Zeitpunkt sowie tatsächlich abgebuchte Dosen.",
  "history.status": "Status",
  "history.intake": "Einnahme",
  "history.scheduled": "Geplant",
  "history.actual": "Tatsächlich",
  "history.deviation": "Abweichung",
  "history.doses": "Dosen",
  "history.deleted_schedule": "Gelöschter Plan",
  "history.empty_title": "Noch kein Verlauf",
  "history.empty_text": "Abgeschlossene und ausgelassene Einnahmen werden hier protokolliert.",
  "history.export_title": "Einnahmeverlauf exportieren",
  "history.export_help": "Exportiert gespeicherte abgeschlossene und ausgelassene Einnahmen im gewählten inklusiven Zeitraum.",
  "history.export_from": "Von",
  "history.export_to": "Bis",
  "history.export_json": "JSON",
  "history.export_csv": "CSV",
  "history.export_empty": "In diesem Zeitraum gibt es keine abgeschlossenen oder ausgelassenen Einnahmen.",
  "history.export_done": "{count} Einnahmevorgang/-vorgänge exportiert.",
  "med_form.eyebrow": "MEDIKAMENT",
  "med_form.edit_title": "Medikament bearbeiten",
  "med_form.new_title": "Neues Medikament",
  "med_form.dialog_label": "Medikament bearbeiten",
  "med_form.name": "Name",
  "med_form.name_placeholder": "z. B. Metformin",
  "med_form.manufacturer": "Hersteller",
  "med_form.manufacturer_placeholder": "z. B. 1A Pharma",
  "med_form.barcode": "Barcode / PZN",
  "med_form.barcode_placeholder": "Scan- oder Artikelnummer",
  "med_form.strength": "Wirkstärke",
  "med_form.strength_placeholder": "z. B. 500 mg",
  "med_form.form": "Darreichungsform",
  "med_form.form_placeholder": "Tablette, Tropfen, …",
  "med_form.unit": "Bestandseinheit",
  "med_form.unit_default": "Stück",
  "med_form.unit_placeholder": "Stück, ml, Hübe, …",
  "med_form.stock_calculated": "Berechneter Bestand",
  "med_form.stock_calculated_help": "Wird immer aus den Restmengen aller Packungen berechnet.",
  "med_form.package_next": "Nach dem Speichern legst du in Schritt 2 die erste physische Packung an.",
  "med_form.threshold": "Warnschwelle",
  "med_form.notes": "Notizen",
  "med_form.notes_placeholder": "Optionale Hinweise",
  "reg_form.eyebrow": "EINNAHMEPLAN",
  "reg_form.edit_title": "Einnahme bearbeiten",
  "reg_form.new_title": "Neue Einnahme",
  "reg_form.dialog_label": "Einnahme bearbeiten",
  "reg_form.name": "Bezeichnung",
  "reg_form.name_placeholder": "z. B. Mittagsmedikation",
  "reg_form.status": "Status",
  "reg_form.medications_dose": "Medikamente & Dosis",
  "reg_form.add_medication": "Weiteres Medikament",
  "reg_form.rhythm": "Rhythmus",
  "reg_form.weekly": "Wöchentlich nach Wochentag",
  "reg_form.interval": "Alle x Tage",
  "reg_form.repeat": "Erneut erinnern nach (Min.)",
  "reg_form.weekdays_times": "Wochentage und Uhrzeiten",
  "reg_form.multiple_times_help": "Mehrere Uhrzeiten mit Komma trennen.",
  "reg_form.interval_title": "Intervall",
  "reg_form.every_days": "Alle x Tage",
  "reg_form.start_date": "Startdatum",
  "reg_form.time": "Uhrzeit",
  "reg_form.notify_services": "Benachrichtigungsdienste",
  "reg_form.notify_placeholder": "notify.mobile_app_mein_handy",
  "reg_form.notify_help": "Mehrere Dienste mit Komma trennen. Aktionsbuttons werden automatisch ergänzt.",
  "reg_form.scripts": "Scripts bei jeder Erinnerung",
  "reg_form.script_placeholder": "script.medikamenten_erinnerung",
  "reg_form.instructions": "Einnahmehinweis",
  "reg_form.instructions_placeholder": "z. B. Mit einem Glas Wasser und zum Essen",
  "reg_form.save": "Plan speichern",
  "reg_form.choose_medication": "Medikament wählen",
  "reg_form.remove": "Entfernen",
  "action.medication_deleted": "Medikament gelöscht.",
  "action.regimen_deleted": "Einnahmeplan gelöscht.",
  "action.reminder_snoozed": "Erinnerung verschoben.",
  "action.reminder_snoozed_until": "Erinnerung bis zur gewählten Zeit verschoben.",
  "action.intake_skipped": "Einnahme als ausgelassen markiert.",
  "action.intake_recorded": "Einnahme gespeichert und Bestand abgebucht.",
  "action.medication_saved": "Medikament gespeichert.",
  "action.regimen_saved": "Einnahmeplan gespeichert.",
  "confirm.delete_medication": "Dieses Medikament wirklich löschen?",
  "confirm.delete_regimen": "Diesen Einnahmeplan wirklich löschen? Offene Vorgänge werden ebenfalls entfernt.",
  "confirm.skip": "Diese Einnahme auslassen? Der Bestand wird nicht verändert.",
  "error.generic": "Die Aktion konnte nicht ausgeführt werden.",
  "error.create_medication_first": "Lege zuerst mindestens ein Medikament an.",
  "error.select_time": "Bitte zuerst eine Uhrzeit auswählen.",
  "error.future_snooze": "Die Schlummerzeit muss in der Zukunft liegen.",
  "error.select_dose": "Wähle mindestens eine Dosis aus.",
  "error.duplicate_medication": "Ein Medikament darf pro Plan nur einmal vorkommen.",
  "error.invalid_time": "Ungültige Uhrzeit bei {day}.",
  "error.select_weekday": "Wähle mindestens einen Wochentag.",
  "error.not_configured": "Medication Reminder ist nicht eingerichtet.",
  "error.medication_in_use": "Dieses Medikament wird noch in einem Einnahmeplan verwendet.",
  "error.dose_exceeds": "Die eingenommene Dosis überschreitet die noch geplante Dosis.",
  "error.not_enough_stock": "Der Bestand von {medication} reicht nicht aus.",
  "error.no_dose": "Es wurde keine Dosis ausgewählt.",
  "error.only_open_snooze": "Nur offene Einnahmen können geschlummert werden.",
  "error.name_required": "Ein Name ist erforderlich.",
  "error.unknown_medication": "Das ausgewählte Medikament existiert nicht mehr.",
  "error.medication_duplicate": "Ein Medikament darf pro Plan nur einmal vorkommen.",
  "error.medication_required": "Mindestens ein Medikament ist erforderlich.",
  "error.repeat_range": "Das Erinnerungsintervall muss zwischen 5 und 1440 Minuten liegen.",
  "error.every_days_range": "Das Tagesintervall muss zwischen 1 und 365 liegen.",
  "error.schedule_type": "Dieser Zeitplantyp wird nicht unterstützt.",
  "error.invalid_snooze": "Die Schlummerzeit ist ungültig.",
  "error.invalid_time_generic": "Eine der eingegebenen Uhrzeiten ist ungültig.",
  "error.invalid_value": "Einer der eingegebenen Werte ist ungültig.",
  "error.export_range": "Wähle einen gültigen Zeitraum. Das Startdatum darf nicht nach dem Enddatum liegen.",
  "app.record_unplanned": "Ungeplante Einnahme",
  "app.delete_all_data": "Alle Medication-Reminder-Daten löschen",
  "app.data_management": "Sichern und wiederherstellen",
  "data.eyebrow": "DATENVERWALTUNG",
  "data.title": "Sichern und wiederherstellen",
  "data.dialog_label": "Medication-Reminder-Daten verwalten",
  "data.export_title": "Vollständiges Backup herunterladen",
  "data.export_help": "Exportiert Medikamente, Packungen, Pläne, offene Tickets und den vollständig gespeicherten Verlauf als JSON.",
  "data.export_button": "Backup herunterladen",
  "data.export_done": "Vollständiges Backup heruntergeladen.",
  "data.import_title": "Vollständiges Backup wiederherstellen",
  "data.import_help": "Wähle ein JSON-Backup, das von dieser Integration erstellt wurde.",
  "data.import_file": "Backup-Datei",
  "data.import_warning": "Der Import ersetzt alle aktuellen Medication-Reminder-Daten. Exportiere den jetzigen Stand zuerst, falls du ihn noch benötigst.",
  "data.import_button": "Importieren und ersetzen",
  "data.import_done": "Backup erfolgreich importiert.",
  "confirm.import_backup": "Alle aktuellen Medication-Reminder-Daten durch dieses Backup ersetzen? Ohne vorherigen Export kann dies nicht rückgängig gemacht werden.",
  "error.backup_file": "Wähle zuerst eine JSON-Backup-Datei aus.",
  "error.backup_invalid": "Das Backup konnte nicht importiert werden. Es ist ungültig, beschädigt oder stammt aus einer nicht unterstützten Version.",
  "stock.automatic": "Automatisch aus Packungen",
  "stock.packages": "Packungen",
  "stock.add_package": "Packung hinzufügen",
  "stock.no_packages": "Noch keine Packungen",
  "stock.next_package": "Zuerst {package} verwenden",
  "package.remaining": "Noch {amount} {unit}",
  "package.initial": "Anfangs {amount} {unit}",
  "package.lot": "LOT {lot}",
  "package.expires": "MHD {date}",
  "package.no_expiry": "Kein MHD angegeben",
  "package.edit": "Packung bearbeiten",
  "package.delete": "Packung löschen",
  "package.code": "QR-Code",
  "package_form.eyebrow": "PHYSISCHE PACKUNG",
  "package_form.new_title": "Packung hinzufügen",
  "package_form.edit_title": "Packung bearbeiten",
  "package_form.dialog_label": "Physische Packung bearbeiten",
  "package_form.medication": "Medikament",
  "package_form.nickname": "Spitzname",
  "package_form.nickname_help": "Leer lassen, damit automatisch ein lustiger freier Name gewählt wird.",
  "package_form.quantity": "Menge",
  "package_form.remaining": "Restmenge",
  "package_form.lot": "LOT- / Chargennummer",
  "package_form.expiry": "MHD / Verfallsdatum",
  "package_form.external_code": "Aufgedruckter Barcode-/QR-/DataMatrix-Inhalt",
  "package_form.external_code_help": "Optionaler Originalcode des Herstellers.",
  "package_form.save": "Packung speichern",
  "package_form.step_two": "Schritt 2 von 2 · Erste Packung anlegen",
  "package_form.step_two_help": "Das Medikament ist gespeichert. Sein Bestand beginnt bei null und erhöht sich, sobald du diese Packung speicherst.",
  "unplanned.eyebrow": "UNGEPLANTE EINNAHME",
  "unplanned.title": "Jetzt genommenes Medikament erfassen",
  "unplanned.dialog_label": "Ungeplante Einnahme erfassen",
  "unplanned.taken_at": "Eingenommen um",
  "unplanned.medications": "Medikamente & tatsächliche Dosen",
  "unplanned.save": "Einnahme erfassen",
  "unplanned.history_name": "Ungeplante Einnahme",
  "ticket.take_from": "Nimm aus {packages}",
  "ticket.postpone_tomorrow": "Zyklus auf morgen verschieben",
  "ticket.qr": "Einnahme-QR-Code",
  "history.packages": "Packungen: {packages}",
  "code.eyebrow": "SCAN-CODE",
  "code.title": "QR-Code für {object}",
  "code.dialog_label": "Generierter Scan-Code",
  "code.help": "Dieser QR-Code enthält nur die unten angezeigte Kurzkennung. Er enthält weder einen Link noch Medikamentendaten.",
  "code.copy": "Kennung kopieren",
  "code.copied": "Kurzkennung kopiert.",
  "code.medication": "Medikament",
  "code.package": "Packung",
  "code.intake": "Einnahme",
  "action.package_saved": "Packung gespeichert und Bestand neu berechnet.",
  "action.package_deleted": "Packung gelöscht und Bestand neu berechnet.",
  "action.unplanned_saved": "Ungeplante Einnahme erfasst und Bestand abgebucht.",
  "action.interval_postponed": "Einnahme und folgende Intervalltermine auf morgen verschoben.",
  "action.all_data_deleted": "Alle Medication-Reminder-Daten wurden gelöscht.",
  "confirm.delete_package": "Diese Packung löschen? Bestehende Einnahmen behalten ihren Packungs-Snapshot.",
  "confirm.postpone_interval": "Diese Einnahme auf morgen und den gesamten Intervallzyklus entsprechend verschieben?",
  "confirm.delete_all_data": "Alle Medikamente, Packungen, Pläne, Tickets und den Verlauf dauerhaft löschen? Die Integration selbst bleibt installiert.",
  "prompt.delete_all_data": "Dies kann nicht rückgängig gemacht werden. Zur Bestätigung DELETE eingeben.",
  "error.package_quantity": "Die Packungsmenge muss größer als null sein.",
  "error.package_nickname": "Packungs-Spitznamen müssen pro Medikament eindeutig sein.",
  "error.unplanned_future": "Die Einnahmezeit darf nicht in der Zukunft liegen.",
  "error.interval_only": "Nur fällige, unberührte Intervall-Einnahmen können auf morgen verschoben werden.",
  "error.qr_failed": "Der QR-Code konnte nicht erzeugt werden.",
  "error.delete_confirmation": "Die Bestätigung stimmt nicht. Es wurden keine Daten gelöscht."
});

export const CATALOGS = Object.freeze({ en: EN, de: DE });

export function resolveLanguage(hass) {
  const requested = String(hass?.language || hass?.locale?.language || "en")
    .toLowerCase().split("-")[0];
  return Object.hasOwn(CATALOGS, requested) ? requested : "en";
}

export function createTranslator(language) {
  const catalog = CATALOGS[language] || EN;
  return (key, variables = {}) => {
    const template = catalog[key] ?? EN[key] ?? key;
    return template.replace(/\{(\w+)\}/g, (_match, name) => String(variables[name] ?? `{${name}}`));
  };
}
